name: Hello World!

on:
  push:
    branchs:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Bonjour a tous!
        run: |
          echo "Bonjour tous le monde!"
      - name: Now it is
        run: date
      - name: ls -l
        run: ls -l
